### ISSUE TITLE
Gap in CAGRA index build time observed between the C++ and python API

### ISSUE THREAD

**Issue by narangvivek10** [SearchScale/lucene-cuvs#3]
We are observing a significant difference in the time it takes to build the CAGRA index using the [C++ API](https://docs.rapids.ai/api/raft/stable/cpp_api/neighbors_cagra/#_CPPv4I000E5build5indexI1T4IdxTERKN4raft9resourcesERK12index_params6mdspanIK1T13matrix_extentI7int64_tE9row_major8AccessorE) as compared to the [Python API](https://docs.rapids.ai/api/raft/stable/pylibraft_api/neighbors/#pylibraft.neighbors.cagra.build). 

Relevant code sections building index and measuring time can be found in [this branch](https://github.com/SearchScale/lucene-cuvs/tree/ishan/experimental-benchmarks):
- https://github.com/SearchScale/lucene-cuvs/blob/e65903ce7deae777e997e527ffd2d2397db69d77/cuda/src/CudaIndexJni.cu#L55-L58
- https://github.com/SearchScale/lucene-cuvs/blob/e65903ce7deae777e997e527ffd2d2397db69d77/benchmarks/python_test.py#L38-L40

To try out:
 - [Install RAFT](https://docs.rapids.ai/api/raft/stable/build/#installation)
 - Checkout the [test branch](https://github.com/SearchScale/lucene-cuvs/tree/ishan/experimental-benchmarks)
 - Download the test dataset using [this script](https://github.com/SearchScale/lucene-cuvs/blob/ishan/experimental-benchmarks/benchmarks/download.sh) script.
 - For C++ API trial:
   ```
   mvn package
   java -jar lucene/target/cuvs-searcher-lucene-0.0.1-SNAPSHOT-jar-with-dependencies.jar wikipedia_vector_dump.csv 3 article_vector 
   1000000 768 query.txt
   ```
 - For Python API trial, in the benchmarks folder:
   ```
   pip install sentence_transformers
   python python_test.py
   ```

A trial on the `RTX 2080 Ti` GPU showed the following gap in the time.
![Screenshot from 2024-04-03 17-10-48_h](https://github.com/SearchScale/lucene-cuvs/assets/123010842/7bcbfd3b-c1f3-4878-be8c-1724cff924de)

**Comment by chatman** [comment]
On RTX 4090, difference is 8s (python) vs 30s (c++ with jni).
